#!/bin/bash 
# utility to remove the test files generated by failing tests

CLEAN_FILES="*.diff *.log *.out *.exp *.php *.sh"

echo "Cleaning tests directory..."
for i in $CLEAN_FILES; do
  if test -f "tests/$i"; then
    rm -f "$i"
    printf "%s" "\ttests/$i";
  fi
done
