#!/bin/bash 
# utility to remove the test files generated by failing tests
SCRIPT=$(readlink -f "$0")
SP=$(dirname "$SCRIPT")
rm $SP/tests/*.diff $SP/tests/*.log $SP/tests/*.out $SP/tests/*.exp $SP/tests/*.php $SP/tests/*.sh
