#!/bin/bash 
# utility to remove the test files generated by failing tests

unset CLEAN_FILES d

while getopts :d opt; do
  case ${opt} in
    d) ((d++)) ;;
    *) ;;
  esac
done

dbgprint() {
  if (( d > 0 )); then
    echo -e "${1}"
  fi
}

CLEAN_FILES=('diff' 'log' 'out' 'exp' 'php' 'sh')

(
  cd tests || exit
  echo "Cleaning tests directory... "
  dbgprint ""

  counter=0
  for i in *; do
    ext="${i##*.}"
    if [[ -f "${i}" && "${CLEAN_FILES[*]}" =~ ${ext} ]]; then
      ((counter++))
      dbgprint "\ttests/${i}"
      rm ${i}
    fi
  done
  dbgprint ""
  echo "Removed ${counter} files"
)
