/*
   +----------------------------------------------------------------------+
   | Copyright (c) The PHP Group                                          |
   +----------------------------------------------------------------------+
   | This source file is subject to version 3.01 of the PHP license,      |
   | that is bundled with this package in the file LICENSE, and is        |
   | available through the world-wide-web at the following url:           |
   | https://www.php.net/license/3_01.txt                                 |
   | If you did not receive a copy of the PHP license and are unable to   |
   | obtain it through the world-wide-web, please send a note to          |
   | license@php.net so we can mail you a copy immediately.               |
   +----------------------------------------------------------------------+
   | Author: Alexander Hedberg <alexander.hedberg@mimer.com>              |
   +----------------------------------------------------------------------+
*/

#ifndef PHP_PDO_MIMER_H
# define PHP_PDO_MIMER_H

/**
 * @brief A macro to put quotes around an integer.
 *
 * This macro exists per PHP's coding standards, see
 * <a href="https://github.com/php/php-src/blob/master/CODING_STANDARDS.md#code-implementation">CODING_STANDARDS.md</a>,
 * list item #4
 *
 * \n e.g.
 *
 * @code
 *     QUOTE(PDO_MIMER_DEFAULT_PORT) -> QUOTE(1306) -> "1306"
 * @endcode
 */
#define QUOTE(x) #x

/**
 * @brief This data structure represents PDO's Data Source Name
 *
 * @info Each char pointer should be a null-terminated string.
 *
 * @code char* optval; // initalize with a default value @endcode
 *
 * @link <a href="https://www.php.net/manual/en/pdo.construct.php">PDO Construct</a>
 */
typedef struct pdo_data_src_parser data_src_opt;

/* TODO: future functionality?
 * #define PDO_MIMER_DEFAULT_PROTOCOL  AMimerProtocol
 * #define PDO_MIMER_DEFAULT_PORT      1306
 * #define PDO_MIMER_DEFAULT_HOST      "localhost"
 * #define PDO_MIMER_DEFAULT_IDENT     "SYSADM"
 * #define PDO_MIMER_DEFAULT_PWD       "SYSADM"
 * #define PDO_MIMER_DEFAULT_CHAR_TYPE char*
 */

/* generated by ext_skel.php */
extern zend_module_entry pdo_mimer_module_entry;
# define phpext_pdo_mimer_ptr &pdo_mimer_module_entry

#include "php_version.h"
# define PHP_PDO_MIMER_VERSION PHP_VERSION

/* TODO: find out what this does */
/* generated by ext_skel.php */
# if defined(ZTS) && defined(COMPILE_DL_PDO_MIMER)
ZEND_TSRMLS_CACHE_EXTERN()
# endif

/* TODO: other drivers have this, maybe instead of ^? Find out what this does.
#ifdef ZTS
#include "TSRM.h"
#endif
*/

/* declare pdo_mimer init/shutdown functions */
PHP_MINIT_FUNCTION(pdo_mimer);
PHP_MSHUTDOWN_FUNCTION(pdo_mimer);
PHP_MINFO_FUNCTION(pdo_mimer);

#endif	/* PHP_PDO_MIMER_H */
