/*
   +--------------------------------------------------------------------------------+
   | MIT License                                                                    |
   +--------------------------------------------------------------------------------+
   | Copyright (c) 2023 Mimer Information Technology AB                             |
   +--------------------------------------------------------------------------------+
   | Permission is hereby granted, free of charge, to any person obtaining a copy   |
   | of this software and associated documentation files (the "Software"), to deal  |
   | in the Software without restriction, including without limitation the rights   |
   | to use, copy, modify, merge, publish, distribute, sublicense, and/or sell      |
   | copies of the Software, and to permit persons to whom the Software is          |
   | furnished to do so, subject to the following conditions:                       |
   |                                                                                |
   | The above copyright notice and this permission notice shall be included in all |
   | copies or substantial portions of the Software.                                |
   |                                                                                |
   | THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR     |
   | IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,       |
   | FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE    |
   | AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER         |
   | LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,  |
   | OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE  |
   | SOFTWARE.                                                                      |
   +--------------------------------------------------------------------------------+
   | Author: Alexander Hedberg <alexander.hedberg@mimer.com>                        |
   +--------------------------------------------------------------------------------+
*/--------------------------------------------------------------------+
*/

#ifndef PHP_PDO_MIMER_H
# define PHP_PDO_MIMER_H

/* generated by ext_skel.php */
extern zend_module_entry pdo_mimer_module_entry;
# define phpext_pdo_mimer_ptr &pdo_mimer_module_entry

#include "php_version.h"
# define PHP_PDO_MIMER_VERSION PHP_VERSION

/* TODO: find out what this does */
# if defined(ZTS) && defined(COMPILE_DL_PDO_MIMER)
ZEND_TSRMLS_CACHE_EXTERN()
# endif

/* TODO: other drivers have this, maybe instead of ^? Find out what this does.
#ifdef ZTS
#include "TSRM.h"
#endif
*/

/* declare pdo_mimer init/shutdown functions */
PHP_MINIT_FUNCTION(pdo_mimer);
PHP_MSHUTDOWN_FUNCTION(pdo_mimer);
PHP_MINFO_FUNCTION(pdo_mimer);

#endif	/* PHP_PDO_MIMER_H */
